program ::= definition*

definition ::= identifier '(' ')' statement* '$'

statement ::= ':' identifier
            | instruction [operand [, operand]*] EOL

operand ::= integer
          | identifier

integer ::= \x+

instruction ::= 'set'
              | 'ret'
	      | 'local'
	      | 'add'
	      | 'jmp'

