program ::= statement*

statement ::= [':' identifier] statement
            | instruction [operand [, operand]*]

operand ::= '$' integer
          | '$' identifier

integer ::= \x+

instruction ::= 'set'
              | 'ret'
	      | 'local'

